"""empty message

Revision ID: 57c9f96d928f
Revises: 6f89fdf4e3fd
Create Date: 2023-02-13 06:37:31.611948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c9f96d928f'
down_revision = '6f89fdf4e3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_problems', sa.Column('Problem_Statement', sa.String(), nullable=True))
    op.add_column('user_problems', sa.Column('due', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_problems', 'due')
    op.drop_column('user_problems', 'Problem_Statement')
    # ### end Alembic commands ###
