"""empty message

Revision ID: f16df5a465b8
Revises: 5ef394fff132
Create Date: 2023-02-12 04:33:20.968745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16df5a465b8'
down_revision = '5ef394fff132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_problems', sa.Column('problem_path', sa.String(), nullable=True))
    op.add_column('user_problems', sa.Column('is_solved', sa.Boolean(), nullable=True))
    op.drop_column('user_problems', 'solved')
    op.drop_column('user_problems', 'problem_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_problems', sa.Column('problem_url', sa.VARCHAR(), nullable=True))
    op.add_column('user_problems', sa.Column('solved', sa.BOOLEAN(), nullable=True))
    op.drop_column('user_problems', 'is_solved')
    op.drop_column('user_problems', 'problem_path')
    # ### end Alembic commands ###
